version: '3'
services:
  cdk:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: sandbox-aws-cdk
    volumes:
      - aws_settings:/root/.aws
    tty: true
volumes:
  aws_settings:
    driver: local